import 'package:flutter/material.dart';
import 'package:aquaman/utilities/constants.dart';

class Ruler extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Wrap(
        // child: Container(
        //   width: 30.0,
        children: [
          Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Row(
              children: [
                Container(
                  margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
                  color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
                  width: kRulerLongWidth(context),
                  height: kRulerHeight(context),
                ),
              ],
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerLongWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            Container(
              margin: EdgeInsets.only(top: kRulerMarginOnlyTop),
              color: Color(kRulerColor).withOpacity(kRulerColorOpacity),
              width: kRulerShortWidth(context),
              height: kRulerHeight(context),
            ),
            // ),
          ]),
        ]);
  }
}
